### ISSUE TITLE
JSON file header regarding exposure time

### ISSUE THREAD

**Issue by HaoyangRong** [HolyLab/ImagineInterface#40]
When writing JSON file, it should write "exposure time in seconds for camera2" instead of "exposure time in seconds" for my Imagine to work as Dae Woo discussed here https://github.com/HolyLab/ImagineInterface/issues/1#issuecomment-318406940.
I'll double check with Dae Woo about how the newest Imagine reads that header field.

**Comment by Cody-G** [comment]
You're right, sorry about that!  After looking into this I realized it's not enough just to change that one header entry.  @kdw503 I think we need to repeat several of the keys in the command file for OCPI2 since the two camera signals may differ a lot depending on the users's supplied waveform.  Here are all of the metadata keys we're currently using, according to the ImagineInterface package:

"samples per second"
**"frames per stack"**
**"stacks"**
"bi-direction"
**"exposure time in seconds"**
"sample num"
"rig"

The entries in bold are the ones for which I think we need to allow the two cameras to differ.  We can suffix each of those entries with " for camera2" and "for camera1" for OCPI2 commands.  Could you implement this with the current Imagine?  There might be additional changes needed to allow the two camera stack sizes and counts to differ.

Another alternative way to lay out this information would be to nest the camera information one level deeper in the JSON.  We could have the keys "camera1 metadata" and "camera2 metadata" and nest the camera info inside of them.  Then we wouldn't have to suffix the bold entries with "for camera1" or "for camera2".  The other (non-bold) entries would not be nested because there's no need to duplicate them.

Let me know how you prefer to implement it and I will mimic that layout in ImagineInterface.

**Comment by kdw503** [comment]
I like nested one.

- And I would like to propose to add "exposure trigger mode" field as below
to specify for which mode the waveform data is generated originally.
"exposure trigger mode" : "External start"
"exposure trigger mode" : "External Control"
"exposure trigger mode" : "Fast External Control"

- In addition, I would like to propose a "generated from" field.
If the JSON file is generated from ImagineInterface package, it would be
"generated from" : "ImagineInterface"
If from Imagine GUI,
"generated from" : "Imagine"
This is  for debugging purpose when the waveform cause some errors. 

- Then final form would be look like..

for ocpi-2
```
{
...
    "metadata": {
        "bi-direction": false,
        "rig": "ocpi-2",
        "generated from" : "ImagineInterface"
        "sample num": 402714,
        "samples per second": 50000,
        "camera 1": {      <--- I think this shorter name would be enough
               "exposure time in seconds": 0.03,
               "exposure trigger mode" : "External start"
               "frames per stack": 20,
               "stacks": 6
        }, 
        "camera 2": {
               "exposure time in seconds": 0.03,
               "exposure trigger mode" : "External start"
               "frames per stack": 20,
               "stacks": 6
        }, 
    },
...
}
```
for ocpi-1
```
{
...
    "metadata": {
        "bi-direction": false,
        "rig": "ocpi-1",
        "generated from" : "ImagineInterface"
        "sample num": 402714,
        "samples per second": 50000,
        "camera 1": {
               "exposure time in seconds": 0.03,
               "exposure trigger mode" : "External start"
               "frames per stack": 20,
               "stacks": 6
        }, 
    },
...
}
```

- And, I think in this case, JSON format version also need to be changed to compatible with older version. It would be better to get more suggestions before we fix this version.
    "version": "v1.1",

**Comment by Cody-G** [comment]
I also like nesting better.  I just pushed [this](https://github.com/HolyLab/ImagineInterface/tree/cjg/cam_meta) branch with a fix that doesn't use the nesting approach, and I think it's uglier than needed.  I won't merge it for now, but I'll leave it as the default branch on the OCPI2 computer until you implement the nested version in Imagine.

I also like the idea of adding "generated from" and "exposure trigger mode" fields.  Could we shorten the entries to "camera1" and "camera2" (no spaces) instead?  That would be consistent with the channel names.

Yes these will be breaking changes, at least on the Imagine side.  So bumping the version to "v1.1" is fine with me.  We can give people a couple of days to give their opinions before we merge anything. 

@HaoyangRong @coolsecu @Callahanra @zhikai-liu  To users: if we do this then you will need to regenerate any existing .json command files that you have.  After the change is implemented in ImagineInterface you can just re-run the scripts that you used to generate your original commands, possibly with a one-line change to the `write_commands` function call at the end.  In order to be clued in better on these things in the future I also suggest "watching" this repository (there's a button for that at the top of the page).

**Comment by kdw503** [comment]
> Could we shorten the entries to "camera1" and "camera2" (no spaces) instead? That would be consistent with the channel names.

Ok, good.

**Comment by kdw503** [comment]
Small change

"exposure trigger mode" : "External start"

-->

"exposure trigger mode" : "External Start"

**Comment by kdw503** [comment]
Does we remove 'camera1' metadata block, if we only use camera2?

**Comment by Cody-G** [comment]
That makes sense to me.
